### ISSUE TITLE
Cannot connect to Debian repos on HAProxy VM

### ISSUE THREAD

**Issue by Pleskan** [natebuckareff/self-managed-k8s#2]
```
W: Failed to fetch mirror+file:/etc/apt/mirrors/debian.list/dists/bookworm/InRelease  Could not connect to debian.map.fastly.net:443 (146.75.118.132), connection timed out Unable to connect to deb.debian.org:https:
```
No matters if IPv4 or IPv6, see previous closed issue.

**Comment by natebuckareff** [comment]
Seems like an issue with the mirror Debian has picked. What happens if you just run `apt-get update` on the VM? Might just need to manually choose a mirror.

**Comment by Pleskan** [comment]
> Seems like an issue with the mirror Debian has picked. What happens if you just run `apt-get update` on the VM? Might just need to manually choose a mirror.

@natebuckareff  issue is exactly the same - external network, the Internet is unreachable.
BTW, I've already enabled forwarding in **sysctl.conf** on the host machine. 
So, it seems that some iptables rule is missing.
**apt update** doesn't work as well.
P.S. Debian repository itself is up and running - I can reach it from the host OS.

**Comment by natebuckareff** [comment]
I was able to reproduce your issue and fixed it by adding a FORWARD `iptables` rule. Let me know if that fixes it for you too. I also refactored the script so it can be run in stages.

**Comment by Pleskan** [comment]
@natebuckareff  Yep, network is works!
Thank you!
