### ISSUE TITLE
k0sctl can't connect: no usable authentication method found

### ISSUE THREAD

**Issue by Pleskan** [natebuckareff/self-managed-k8s#3]
```
INFO ==> Running phase: Connect to hosts 
FATA apply failed - log file saved to /root/.cache/k0sctl/k0sctl.log: failed on 3 hosts:
 - [ssh] 10.0.0.12:22: retrying aborted
not connected: client connect: can't connect: create config: can't connect: no usable authentication method found
 - [ssh] 10.0.0.11:22: retrying aborted
not connected: client connect: can't connect: create config: can't connect: no usable authentication method found
 - [ssh] 10.0.0.10:22: retrying aborted
not connected: client connect: can't connect: create config: can't connect: no usable authentication method found 
+ k0sctl kubeconfig --config ./build/k0sctl.yaml
+ mkdir -p /root/.kube
+ KUBECONFIG=./build/kubeconfig
+ kubectl config view --flatten
error: error loading config file "./build/kubeconfig": yaml: mapping values are not allowed in this context
+ set -e
```
That the output from the **k0sctl** starting routines.
What's going wrong?

**Comment by Pleskan** [comment]
Might be related to[ this ](https://github.com/k0sproject/k0sctl/issues/462) issue

**Comment by Pleskan** [comment]
Yep, it seems like a bug in **k0s** .
I can reproduce it even there is only one private key in my **ssh_config**

`IdentityFile ~/.ssh/id_ed25519`
Error is the same, no changes.

**Comment by natebuckareff** [comment]
Hmm, I'm not able to reproduce this.

Ky `k0sctl` version:

```
$ k0sctl version
version: v0.16.0
commit: 7e8c272
```

Note that the `config.json` file needs to point at your public key and is currently hardcoded to "~/.ssh/id_ed25519.pub".

I also tried making my `~/.ssh/config` empty, adding `Host` blocks for the VMs using `IdentityFile ~/.ssh/id_ed25519` and also empty except for just a single `IdentityFile` statement.

It's possible I'm just not understanding the linked issue here. I'm not using tailscale, just connecting locally. Are you connecting through tailscale?

**Comment by Pleskan** [comment]
No, I'm connecting directly too.

I know what might be causing the problem: I run all the scripts with the **sudo** .

Close this issue for now.

**Comment by Pleskan** [comment]
Unfortunately, no, the issue is still there.
I've got no clues as to it.
For regular user, the problem persists.
My host OS is **Kubuntu 22.04.3**.
The k0sctl version and commit are the same as yours.

**Comment by natebuckareff** [comment]
I was going to suggest testing with a k0sctl binary built from main, but it looks like the fix for that issue is already in v0.16.0. So it must be something else.

Some thoughts:
- Is your SSH key password protected?
- Can you share your `~/.cache/k0sctl/k0sctl.log` file?

**Comment by natebuckareff** [comment]
Could run `k0sctl kubeconfig --debug --config ./build/k0sctl.yaml` manually to enable debug tracing. That'll give some more information. You can use the `generate_k0sctl_config.sh` to generate the `./build/k0sctl.yaml`.

**Comment by Pleskan** [comment]
> I was going to suggest testing with a k0sctl binary built from main, but it looks like the fix for that issue is already in v0.16.0. So it must be something else.
> 
> Some thoughts:
> 
>     * Is your SSH key password protected?
> 
>     * Can you share your `~/.cache/k0sctl/k0sctl.log` file?

- No, the key is not  protected;
- Sure, grab it  [here](https://pastebin.com/ceRxdMYy) ;

**Comment by Pleskan** [comment]
> k0sctl kubeconfig --debug --config ./build/k0sctl.yaml

```

DEBU[0000] Preparing phase 'Connect to hosts'           
INFO[0000] ==> Running phase: Connect to hosts 
DEBU[0000] [ssh] 10.0.0.10:22: HashKnownHosts is set to "yes", will hash newly added keys 
DEBU[0000] using SSH_AUTH_SOCK=/tmp/ssh-XXXXXXjhx1YV/agent.1458 
DEBU[0000] [ssh] 10.0.0.10:22: file /home/tony/.ssh/id_ed25519.pub is a public key 
DEBU[0000] [ssh] 10.0.0.10:22: failed to obtain a signer for identity /home/tony/.ssh/id_ed25519.pub: can't connect: signer not found for public key 
DEBU[0000] [SSH] 10.0.0.10: failed to connect: can't connect: create config: can't connect: no usable authentication method found 
FATA[0000] getting kubeconfig failed - log file saved to /home/tony/.cache/k0sctl/k0sctl.log: failed on 1 hosts:
 - [ssh] 10.0.0.10:22: retrying aborted
not connected: client connect: can't connect: create config: can't connect: no usable authentication method found

```

**Comment by natebuckareff** [comment]
Noticing that our logs first differ at line #9. In your log:

`failed to obtain a signer for identity [...] can't connect: signer not found
for public key`

[And in mine](https://pastebin.com/gjKjZGKP):

`signer for public key available in ssh agent`

Went back and checked the docs for the k0sctl config file, [specifically what
it says about `keyPath`](https://github.com/k0sproject/k0sctl?tab=readme-ov-file#spechostssshkeypath-string-optional-default-sshidentity-sshid_rsa-sshid_dsa):

> Path to an SSH key file. **If a public key is used, ssh-agent is required**. When left empty, the default value will first be looked for from the ssh configuration (default ~/.ssh/config) IdentityFile parameter.

The script is just passing the public key - not private - from `config.json`, so maybe it's an issue with `ssh-agent`?

I updated so it now uses a private key instead of public. Everything still works the same for me, but I can confirm that in my k0sctl log file there's no longer anything about using ssh agent. Instead I see:

`using an unencrypted private key from [...]`

**Comment by Pleskan** [comment]
It's weird, but looks like it's true. Something is wrong with ssh-agent, but it installed.
```
ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-XXXXXXnBgz5w/agent.2398; export SSH_AUTH_SOCK;
SSH_AGENT_PID=2399; export SSH_AGENT_PID;
echo Agent pid 2399;
```
Thanks for help :-)

**Comment by Pleskan** [comment]
So, finally, I can confirm that everything works on my side.
I appreciate your help and our collaboration on this 👍

**Comment by natebuckareff** [comment]
Excellent! Glad to hear everything is now working. I really appreciate you opening these issues. It elevated the quality of this repo.
